name: Build documentation
on:
  push:
    branches: '*'
  workflow_dispatch:
permissions:
  id-token: write
  pages: write
env:
  INSTANCE: docs/c
  ARTIFACT: webHelpC2-all.zip
  DOCKER_VERSION: 2.1.1479-p3869
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build docs docs using Docker
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
          retention-days: 7
      - name: test
        run: |
          git ls-files